#!/usr/bin/env ruby

require 'erb'
require 'tempfile'

$formula_template = <<~EOF
  require 'formula'
  require 'fileutils'

  class GoGetDownloadStrategy < AbstractDownloadStrategy
    def initialize(name, resource)
      super
      @gopath = HOMEBREW_CACHE/cache_filename
    end

    def fetch
      ohai "Fetching \#{@url}"
      go_get_package
    end

    def stage
      super
      cp_r File.join(cached_location, "."), Dir.pwd, preserve: true
    end

    def cache_filename
      "\#{@url.gsub(/[.\\/]/, '-')}--gopath"
    end

    def cached_location
      @gopath
    end

    private

    def go_get_package
      ENV['GOPATH'] = cached_location
      safe_system "go", "get", "-u", "-d", @url
    end
  end

  class <%= klass %> < Formula
    url "<%= name %>", :using => GoGetDownloadStrategy
    version "<%= version %>"

    depends_on "go" => :build

    def install
      install_with_gopath
    end

    def install_with_gopath
      ENV["GOPATH"] = buildpath
      ENV["GOBIN"] = bin
      ENV.prepend_create_path "PATH", buildpath/"bin"

      cd buildpath/"src/<%= name %>" do
        system "go", "install", "<%= name %>"
        prefix.install_metafiles
      end
    end

    def test
      false
    end
  end
EOF

module GoInstallerCli
  module_function

  @usage = <<~EOF
    brew go install [package]
    brew go formula [package]

    Usage:
    Manages Go tools using Homebrew formulas.
  EOF

  def help_msg
    @usage
  end

  def process_args(args)
    abort help_msg unless args[0]

    if args[0] == "help"
      STDERR.puts help_msg
      exit 0
    end

    args[0..1]
  end

  def expand_formula(name, version)
    klass           = 'Go' + name.split("/").last.capitalize.gsub(/[-_.\s]([a-zA-Z0-9])/) { $1.upcase }.gsub('+', 'x')
    template        = ERB.new($formula_template)
    template.result(binding)
  end

  def with_temp_formula(name, version)
    filename = File.join Dir.tmpdir, "go-#{name.split("/").last}.rb"

    open(filename, 'w') do |f|
      f.puts expand_formula(name, version)
    end

    yield filename
  ensure
    File.unlink filename
  end

  def run(args = ARGV)
    command, package = process_args(args)
    version = "devel"

    with_temp_formula(package, version) do |filename|
      case command
      when "formula"
        $stdout.puts File.read(filename)
      else
        system "brew #{command} #{filename}"
        exit $?.exitstatus unless $?.success?
      end
    end
  end
end

GoInstallerCli.run(ARGV)
